services:
  db:
    image: mariadb:10.11.7
    container_name: mdb10117
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: mypass
      SERVICE_NAME: mysql
    ports:
      - "3307:3306"
    volumes:
      - mdb10117:/var/lib/mysql
    
    networks:
      - db_mdbs

networks:
  db_mdbs:
    name: mdb10117_service
    # uncomment satu baris "driver: bridge" jika ada masalah dengan koneksi
    driver: bridge

volumes:
  mdb10117:
    name: mdb10117-data
    # uncomment satu baris "driver: bridge" jika ada masalah dengan koneksi
    driver: bridge
