# version: "3.0"
services:
  db:
    image: mariadb:10.11.7
    container_name: mdb10117_service
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: mypass
      SERVICE_NAME: mysql
    ports:
      - "3307:3306"
    volumes:
      - mdb3307:/var/lib/mysql
    
    networks:
      - db_mdbs

networks:
  db_mdbs:
    # uncomment satu baris "driver: bridge" jika ada masalah dengan koneksi
    # driver: bridge
    name: db_service

volumes:
  mdb3307:
    # uncomment satu baris "driver: bridge" jika ada masalah dengan koneksi
    # driver: bridge
